app = "eld-backend"
primary_region = "lhr"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DJANGO_SETTINGS_MODULE = "core.settings"

[[services]]
  protocol = "tcp"
  internal_port = 8000

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.http_checks]]
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/"
    protocol = "http"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
